### ISSUE TITLE
Srcset first cover image

### ISSUE THREAD

**Issue by DanielleCuppen** [Brickson/Website#13]
Final pass: removed scrcset values to close to be of real use

img src="plaatjenaam-568w.jpg"
      alt=""
      sizes="(min-width:2048px) 1365px, /768h
             (min-width:1536px) 1536px, /1024h
             (min-width:1280px) 640px, /480h
             (min-width:1024px) 512px, /768h
             (min-width:768px) 768px, /547h
             (min-width:568px) 568px /370h, 320px /568h”
     srcset=“plaatjenaam-320w.jpg,320w,
     		 plaatjenaam-568w.jpg 568w,
	 		 plaatjenaam-768w.jpg 768w,
	 		 plaatjenaam-1024w.jpg 1024w,
	 		 plaatjenaam-1280w.jpg 1280w,
	 		 plaatjenaam-1536w.jpg 1536w,
	 		 plaatjenaam-3072w.jpg 3072w” />
	 		 
-------------------------	 		 
Fourth pass	? dc did remove a lot, therefore a backup	 		 
	 		        
 <img src="plaatjenaam-568w.jpg"
      alt=""
      sizes="(min-width:2048px) 1365px, /768h
             (min-width:1536px) 1536px, /1024h
             (min-width:1280px) 640px, /480h
             (min-width:1024px) 512px, /768h
             (min-width:768px) 768px, /547h
             (min-width:568px) 568px /370h, 320px /568h”

     srcset=“plaatjenaam-320w.jpg,320w,
     		 plaatjenaam-568w.jpg 568w,
	 		 plaatjenaam-768w.jpg 768w,
	 		 plaatjenaam-512w.jpg 512w,
	 		 plaatjenaam-640w.jpg 640w,
	 		 plaatjenaam-1024w.jpg 1024w,
	 		 plaatjenaam-1136w.jpg 1136w,
	 		 plaatjenaam-1280w.jpg 1280w,
	 		 plaatjenaam-1365w.jpg 1365w,
	 		 plaatjenaam-1536w.jpg 1536w,
	 		 plaatjenaam-2730w.jpg 2730w,
	 		 plaatjenaam-3072w.jpg 3072w” />

**Comment by babsgosgens** [comment]
Tnx - I will render the images
