### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by babsgosgens** [Brickson/website#19]
'Over Brickson/Over ons' wordt 'Contact'

'Werken bij …' vervalt

Volgorde wordt: 'Contact' 'Cases'

**Comment by Leijten** [comment]
pushed to branch feature/19-menu last commit d61c2175f6f8d7621a4f7ee81b3af9fa59c20911

**Comment by babsgosgens** [comment]
Ik zie nog steeds hetzelfde?

**Comment by babsgosgens** [comment]
Fixed.
