### ISSUE TITLE
Shop images

### ISSUE THREAD

**Issue by babsgosgens** [Brickson/website#23]
Please insert correct images for shops:

[...]--ontdekken.jpg
[...]--bedenken.jpg
[...]--ontwerpen.jpg
[...]--bouwen.jpg

This is the correct picture call:

`<picture class="cover__image">
          
          <source
            media="<?php echo $gt_large_handheld; ?>,<?php echo $landscape; ?>"
            sizes="<?php echo $gt_large_handheld; ?> 100vw, 100vw"
            srcset="/images/content/w800px_h320px_3x--cta.jpg 2400w, /images/content/w800px_h320px_2x--cta.jpg 1600w, /images/content/w800px_h320px--cta.jpg 800w">
          <source
            media="<?php echo $gt_small_handheld; ?>,<?php echo $portrait; ?>"
            sizes="<?php echo $gt_small_handheld; ?> 100vw, 100vw"
            srcset="/images/content/w414px_h414px_3x--cta.jpg 1242w, /images/content/w414px_h414px_2x--cta.jpg 828w, /images/content/w414px_h414px--cta.jpg 414w">
          
          <img class="cover__image" src="images/content/w414px_h206px--cta.jpg" alt="">
        </picture>`

**Comment by Leijten** [comment]
Completed in following commits
9696d92d72edbc92f821c9089a65e038d4ae220f
6502a94633a4d106c62b27fdd8c79eafa6ed2f8f
bb3f58a52024861990f3c8b8a17c0cbb0d7f998d
44f8915a36794e65eafe1526cea0bfae1568c072
